### ISSUE TITLE
Manual Recovery w/ Seed Phrase

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-wallet#156]
## Story

As a user, I want the option to backup and recover my account manually with a seed phrase, so I can avoid giving out my phone number or having my private key stored on a server.

## Acceptance Criteria

- [x] User can generate a full access key with an associated seed phrase
- [x] User can click a button to copy seed phrase
- [x] User can recover account by entering seed phrase
- [x] Mobile ok
- [x] Tested

## Assets

- [User Flow](https://docs.google.com/document/d/1G48xFj_87nmeyl9DSAIjVufITlneILre0CijTtaFm_c/edit?usp=sharing)

## TODO
- Mockups/Designs
- Find seed phrase (BIP39) generating library

**Comment by kcole16** [comment]
Closed by #251
